### ISSUE TITLE
No clipboard WP after end of trail in FGS

### ISSUE THREAD

**Issue by bluenote73** [LadyElyssa/LadyElyssaTacoTrails#16] opened 2023-11-12 16:30 UTC
When I get to the end of the path (heart) in Frostgorge Sound Arundon Vale area there doesn't seem to be any instruction or clipboard action. From looking at the trail I think it should be go back to highpeaks.
Love your pack, it's so helpful to me. Thanks :)

**Comment by LadyElyssa** [comment] 2023-11-15 00:22
Thank you for letting me know and you were spot on. The issue is now fixed.

Glad to hear you are enjoying the pack and thanks again for the feedback.

**Comment by bluenote73** [comment] 2023-11-15 00:30
FWIW I ran into a small handful of others but I started to wonder if it was somehow not a mistake so I didn't make a note of them. In future I will and report back :)  But it might take a while for me to work up the courage to do another completion. :)  anyway thanks

**Comment by LadyElyssa** [comment] 2023-11-15 00:41
Thank you anyway and I presume it was the maps leading up to FGS but if you happen to remember which map(s) had an issue it would still be a great help.  Good luck with the rest of your map completion and hope it goes smoothly.

It can all start to become a bit of a blur after a while between the trails, markers, waypoints and all the hearts and I do need to do another full run again myself someone point soon-ish.

**Closed** 2023-11-20 20:38 UTC
